// SPDX-License-Identifier: GPL-3.0-or-later
// Vendored from jblanchette/wc3v (GPL-3.0) at commit 87edeef1f77a8c6f9896b8844990f5b74f6313a0.
// Source: https://github.com/jblanchette/wc3v
// Copyright (C) original wc3v contributors (Jeff Blanchette et al.)
// See src/lib/wc3v/README.md for scope, provenance, and integration notes,
// and docs/adr/012-wc3v-fork-integration.md for the integration decision.
// PATCHED (08-13 GO decision): w3gjs internal-path references repointed from
// the upstream 3.0.0-era `dist/lib/...` layout to the installed 4.1.0
// `dist/cjs/...` layout where this file required it -- see inline comments.

/**
 * Building footprint helpers — derived from the pathing manifest.
 *
 * The authoritative source is `helpers/buildingPathing.json`, generated by
 * `tools/parse-building-pathing.js` from WC3's `PathTextures\*.tga` (extracted
 * via CASC). There is no fallback heuristic — buildings without a manifest
 * entry will throw, which is intentional: it forces the data pipeline to be
 * complete and correct.
 */

const manifest = require('./buildingPathing.json');

function getBuildingWpmFootprint (itemId) {
  const entry = manifest.buildings[itemId];
  if (!entry) {
    throw new Error('No pathing manifest entry for itemId="' + itemId +
                    '". Re-run tools/parse-building-pathing.js.');
  }
  return entry.widthCells;  // returned for square-footprint callers (placement heuristics)
}

function getBuildingTileFootprint (itemId) {
  const entry = manifest.buildings[itemId];
  if (!entry) {
    throw new Error('No pathing manifest entry for itemId="' + itemId + '"');
  }
  return entry.widthCells / 4;
}

function getBuildingFootprintDims (itemId) {
  const entry = manifest.buildings[itemId];
  if (!entry) {
    throw new Error('No pathing manifest entry for itemId="' + itemId + '"');
  }
  return {
    widthCells: entry.widthCells,
    heightCells: entry.heightCells,
    widthTiles: entry.widthCells / 4,
    heightTiles: entry.heightCells / 4
  };
}

module.exports = {
  getBuildingWpmFootprint,
  getBuildingTileFootprint,
  getBuildingFootprintDims
};
