// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 WC3 Roadmap contributors

/**
 * Cross-document content validation orchestrator.
 *
 * Imports the generated node corpus (from the "content-collections" module)
 * and runs four always-on validators:
 *   1. validatePrerequisiteIds — every prereq ID must reference an existing node
 *   2. validatePatchIds        — every patchId must be in the registry
 *   3. detectCycles            — the prerequisite graph must be a DAG
 *   4. validatePathwayStepIds  — every step in pathways/beginner-fundamentals.json
 *                                must reference an existing node (T-02-07 / T-02-08)
 *
 * Three additional LAUNCH-GATE validators run ONLY when the LAUNCH_GATE env
 * flag is set (via `npm run validate:launch`, the release/deploy gate). The
 * always-on `npm run validate` (per-PR CI) skips them, so the codebase stays
 * mergeable while the parallel content workstream flips nodes to launch_ready:
 *   5. validateLaunchGate                 — >= 25 launch_ready nodes (CONT-04)
 *   6. validatePathwayStepsAreLaunchReady — every pathway step is launch_ready (PATH-02)
 *   7. validateAuditTrail                 — every launch_ready node has an auditNote (CONT-05)
 *
 * IMPORTANT BUILD ORDERING: This script imports from the "content-collections"
 * module alias which resolves to .content-collections/generated/index.js.
 * That file is generated by `npm run build:content` (content-collections build).
 * You MUST run build:content before this script, otherwise the import fails.
 * The CI workflow (see .github/workflows/ci.yml) enforces this ordering.
 *
 * Exits non-zero with a clear error list on any validation failure.
 * Exits 0 and prints a pass summary on success.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
// Generated module — requires `npm run build:content` to have run first (Pitfall 4).
import { allNodes } from "content-collections";
import { PathwaySchema } from "../src/schemas/pathway";
import { PATCH_IDS } from "../src/lib/patches";
import { detectCycles } from "./lib/detectCycles";
import { validatePrerequisiteIds, validatePatchIds } from "./lib/validators";
import { validatePathwayStepIds } from "./validate-pathway";
import {
  validateAuditTrail,
  validateLaunchGate,
  validatePathwayStepsAreLaunchReady,
} from "./validate-launch-gate";

function main(): void {
  const errors: string[] = [];

  // 1. Prerequisite ID resolution — cross-document check (DATA-05)
  const prereqErrors = validatePrerequisiteIds(allNodes);
  errors.push(...prereqErrors);

  // 2. patchId referential integrity — belt-and-suspenders (DATA-04 / DATA-07)
  const patchErrors = validatePatchIds(allNodes, PATCH_IDS);
  errors.push(...patchErrors);

  // 3. Prerequisite graph acyclicity — DAG invariant (D-09)
  const cycleErrors = detectCycles(allNodes);
  errors.push(...cycleErrors);

  // 4. Pathway referential integrity — every step must resolve to a real node (T-02-07 / T-02-08)
  const pathwayFile = resolve(process.cwd(), "pathways/beginner-fundamentals.json");
  const pathwayRaw = JSON.parse(readFileSync(pathwayFile, "utf-8")) as unknown;
  const pathwayResult = PathwaySchema.safeParse(pathwayRaw);
  if (!pathwayResult.success) {
    errors.push(
      `pathways/beginner-fundamentals.json failed schema validation: ${pathwayResult.error.message}`
    );
  } else {
    const nodeIds = new Set(allNodes.map((n) => n.id));
    const pathwayErrors = validatePathwayStepIds(pathwayResult.data, nodeIds);
    errors.push(...pathwayErrors);
  }

  // 5/6/7. Launch-readiness gate — enforced ONLY at the deploy gate (LAUNCH_GATE=1).
  // Skipped by the always-on per-PR validate script so CI stays green while the
  // parallel content workstream flips nodes to launch_ready (D-11/D-12).
  if (process.env.LAUNCH_GATE) {
    // 5. >= 25 launch_ready nodes (CONT-04)
    errors.push(...validateLaunchGate(allNodes));
    // 6. every beginner-fundamentals pathway step is itself launch_ready (PATH-02 / Pitfall 5)
    if (pathwayResult.success) {
      errors.push(
        ...validatePathwayStepsAreLaunchReady(pathwayResult.data, allNodes)
      );
    }
    // 7. every launch_ready node carries its recorded audit verdict (CONT-05 / D-13)
    errors.push(...validateAuditTrail(allNodes));
  }

  if (errors.length > 0) {
    console.error("\n=== Content Validation Errors ===");
    for (const error of errors) {
      console.error(`  x ${error}`);
    }
    console.error(`\n${errors.length} error(s) found. Fix before merging.`);
    process.exit(1);
  }

  console.log(
    `Content validation passed (${allNodes.length} node(s) checked, pathway integrity verified).`
  );
}

main();
