// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 WC3 Roadmap contributors

/**
 * Cross-document content validation orchestrator.
 *
 * Imports the generated node corpus (from the "content-collections" module)
 * and runs three validators:
 *   1. validatePrerequisiteIds — every prereq ID must reference an existing node
 *   2. validatePatchIds        — every patchId must be in the registry
 *   3. detectCycles            — the prerequisite graph must be a DAG
 *
 * IMPORTANT BUILD ORDERING: This script imports from the "content-collections"
 * module alias which resolves to .content-collections/generated/index.js.
 * That file is generated by `npm run build:content` (content-collections build).
 * You MUST run build:content before this script, otherwise the import fails.
 * The CI workflow (see .github/workflows/ci.yml) enforces this ordering.
 *
 * Exits non-zero with a clear error list on any validation failure.
 * Exits 0 and prints a pass summary on success.
 */

// Generated module — requires `npm run build:content` to have run first (Pitfall 4).
import { allNodes } from "content-collections";
import { PATCH_IDS } from "../src/lib/patches";
import { detectCycles } from "./lib/detectCycles";
import { validatePrerequisiteIds, validatePatchIds } from "./lib/validators";

function main(): void {
  const errors: string[] = [];

  // 1. Prerequisite ID resolution — cross-document check (DATA-05)
  const prereqErrors = validatePrerequisiteIds(allNodes);
  errors.push(...prereqErrors);

  // 2. patchId referential integrity — belt-and-suspenders (DATA-04 / DATA-07)
  const patchErrors = validatePatchIds(allNodes, PATCH_IDS);
  errors.push(...patchErrors);

  // 3. Prerequisite graph acyclicity — DAG invariant (D-09)
  const cycleErrors = detectCycles(allNodes);
  errors.push(...cycleErrors);

  if (errors.length > 0) {
    console.error("\n=== Content Validation Errors ===");
    for (const error of errors) {
      console.error(`  x ${error}`);
    }
    console.error(`\n${errors.length} error(s) found. Fix before merging.`);
    process.exit(1);
  }

  console.log(`Content validation passed (${allNodes.length} node(s) checked).`);
}

main();
