/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewPathwayRouteImport } from './routes/preview/pathway'
import { Route as PreviewMobileRouteImport } from './routes/preview/mobile'
import { Route as PreviewMasteryStatesRouteImport } from './routes/preview/mastery-states'
import { Route as PreviewFullMapRouteImport } from './routes/preview/full-map'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewPathwayRoute = PreviewPathwayRouteImport.update({
  id: '/preview/pathway',
  path: '/preview/pathway',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewMobileRoute = PreviewMobileRouteImport.update({
  id: '/preview/mobile',
  path: '/preview/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewMasteryStatesRoute = PreviewMasteryStatesRouteImport.update({
  id: '/preview/mastery-states',
  path: '/preview/mastery-states',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewFullMapRoute = PreviewFullMapRouteImport.update({
  id: '/preview/full-map',
  path: '/preview/full-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview/full-map': typeof PreviewFullMapRoute
  '/preview/mastery-states': typeof PreviewMasteryStatesRoute
  '/preview/mobile': typeof PreviewMobileRoute
  '/preview/pathway': typeof PreviewPathwayRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview/full-map': typeof PreviewFullMapRoute
  '/preview/mastery-states': typeof PreviewMasteryStatesRoute
  '/preview/mobile': typeof PreviewMobileRoute
  '/preview/pathway': typeof PreviewPathwayRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview/full-map': typeof PreviewFullMapRoute
  '/preview/mastery-states': typeof PreviewMasteryStatesRoute
  '/preview/mobile': typeof PreviewMobileRoute
  '/preview/pathway': typeof PreviewPathwayRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview/full-map'
    | '/preview/mastery-states'
    | '/preview/mobile'
    | '/preview/pathway'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview/full-map'
    | '/preview/mastery-states'
    | '/preview/mobile'
    | '/preview/pathway'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/preview/full-map'
    | '/preview/mastery-states'
    | '/preview/mobile'
    | '/preview/pathway'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewFullMapRoute: typeof PreviewFullMapRoute
  PreviewMasteryStatesRoute: typeof PreviewMasteryStatesRoute
  PreviewMobileRoute: typeof PreviewMobileRoute
  PreviewPathwayRoute: typeof PreviewPathwayRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/pathway': {
      id: '/preview/pathway'
      path: '/preview/pathway'
      fullPath: '/preview/pathway'
      preLoaderRoute: typeof PreviewPathwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/mobile': {
      id: '/preview/mobile'
      path: '/preview/mobile'
      fullPath: '/preview/mobile'
      preLoaderRoute: typeof PreviewMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/mastery-states': {
      id: '/preview/mastery-states'
      path: '/preview/mastery-states'
      fullPath: '/preview/mastery-states'
      preLoaderRoute: typeof PreviewMasteryStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/full-map': {
      id: '/preview/full-map'
      path: '/preview/full-map'
      fullPath: '/preview/full-map'
      preLoaderRoute: typeof PreviewFullMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewFullMapRoute: PreviewFullMapRoute,
  PreviewMasteryStatesRoute: PreviewMasteryStatesRoute,
  PreviewMobileRoute: PreviewMobileRoute,
  PreviewPathwayRoute: PreviewPathwayRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
